name: .NET CI/CD

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./ECommerce.Integration.sln

      - name: Build
        run: dotnet build ./ECommerce.Integration.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./ECommerce.Integration.sln --no-build --verbosity normal --configuration Release

      - name: Publish
        run: dotnet publish ./src/ECommerce.API/ECommerce.API.csproj --configuration Release --output ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t katana-luca-integration:latest .

      - name: Test Docker compose
        run: |
          docker-compose config
          docker-compose build
